# Generated by Django 5.2.7 on 2026-02-28 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'complaint_category',
            },
        ),
        migrations.CreateModel(
            name='DormitoryBuilding',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'dormitory_building',
            },
        ),
        migrations.CreateModel(
            name='DormitoryFloor',
            fields=[
                ('floor_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.dormitorybuilding')),
            ],
            options={
                'db_table': 'dormitory_floor',
            },
        ),
        migrations.CreateModel(
            name='DormitoryRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.dormitoryfloor')),
            ],
            options={
                'db_table': 'dormitory_room',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=255)),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.dormitoryroom')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('published', 'Опубліковано'), ('denied', 'Відхилено'), ('resolved', 'Вирішено')], default='pending', max_length=50)),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='complaint_photos/')),
                ('counter', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaintcategory')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='complaints.dormitoryroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.userprofile')),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.userprofile')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='ComplaintVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='complaints.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.userprofile')),
            ],
            options={
                'db_table': 'complaint_vote',
                'unique_together': {('user', 'complaint')},
            },
        ),
    ]
