# Generated by Django 5.2.7 on 2026-07-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0010_alter_complaint_category_alter_complaint_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="dormitorybuilding",
            name="commandant_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="dormitorybuilding",
            name="duty_master_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
