# Generated by Django 5.2.7 on 2026-07-10 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0012_userprofile_building"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("worker_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "db_table": "worker",
            },
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="user",
        ),
        migrations.AddField(
            model_name="ticket",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="complaints.worker",
            ),
        ),
    ]
