# Generated by Django 5.2.7 on 2026-07-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0014_delete_worker_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="capacity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="place",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
    ]
