# Generated by Django 5.2.7 on 2026-07-16 16:34

from django.db import migrations, models


def backfill_resolved_at(apps, schema_editor):
    # Existing resolved complaints predate this field. Seed resolved_at from
    # created_at so they aren't invisible in the completed-tickets report. This
    # is a best-effort approximation (we have no true resolution timestamp for
    # historical rows); new resolutions stamp the real time.
    Complaint = apps.get_model("complaints", "Complaint")
    Complaint.objects.filter(status="resolved", resolved_at__isnull=True).update(
        resolved_at=models.F("created_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0015_place_capacity_place_is_shared"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_resolved_at, migrations.RunPython.noop),
    ]
