# Generated by Django 5.2.7 on 2026-07-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_complaint_resolved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitorybuilding',
            name='duty_master_phone',
        ),
    ]
