# Generated by Django 5.2.7 on 2026-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0020_remove_dormitorybuilding_duty_master_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
