# Generated by Django 5.2.7 on 2026-08-22 08:06

import django.db.models.deletion
from django.db import migrations, models


def map_legacy_status(apps, schema_editor):
    """Dev/staging rows carrying the retired vocabulary get mapped onto the
    canonical slugs; fresh databases simply have nothing to update."""
    Complaint = apps.get_model("complaints", "Complaint")
    Complaint.objects.filter(status="published").update(status="approved")
    Complaint.objects.filter(status="denied").update(status="rejected")


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0020_remove_dormitorybuilding_duty_master_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="complaint",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_complaints",
                to="complaints.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="follow_up_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="follow_ups",
                to="complaints.complaint",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="rework_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="follow_up_chain",
                to="complaints.complaint",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="work_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="complaints.worker",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worker",
                to="complaints.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Очікує"),
                    ("approved", "Схвалено"),
                    ("in_progress", "В роботі"),
                    ("review", "На перевірці"),
                    ("resolved", "Вирішено"),
                    ("rejected", "Відхилено"),
                    ("not_accepted", "Не прийнято"),
                    ("withdrawn", "Скасовано"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.RunPython(map_legacy_status, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ComplaintEvent",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assigned", "Призначено"),
                            ("unassigned", "Знято з виконання"),
                            ("reassigned", "Перепризначено"),
                            ("started", "Взято в роботу"),
                            ("started_undo", "Скасовано початок робіт"),
                            ("finished", "Виконано"),
                            ("finished_undo", "Скасовано виконання"),
                            ("archived", "Архівовано"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaint_events",
                        to="complaints.userprofile",
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="complaints.complaint",
                    ),
                ),
            ],
            options={
                "db_table": "complaint_event",
                "ordering": ["created_at", "event_id"],
            },
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
