# Generated by Django 5.2.7 on 2026-08-22 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0021_complaint_archived_complaint_archived_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingTransitionNotice",
            fields=[
                ("notice_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("ready_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "pending_transition_notice",
            },
        ),
        migrations.AddConstraint(
            model_name="complaint",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["pending", "approved", "in_progress", "review", "resolved"],
                    )
                ),
                fields=("follow_up_of",),
                name="unique_open_follow_up_per_source",
            ),
        ),
        migrations.AddField(
            model_name="pendingtransitionnotice",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_notices",
                to="complaints.complaint",
            ),
        ),
        migrations.AddField(
            model_name="pendingtransitionnotice",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_transition_notices",
                to="complaints.userprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingtransitionnotice",
            constraint=models.UniqueConstraint(
                fields=("complaint", "recipient"),
                name="unique_pending_notice_per_recipient",
            ),
        ),
    ]
