# Generated by Django 5.2.7 on 2026-08-24 20:21

import django.db.models.deletion
from django.db import migrations, models


def recreate_worker_role(apps, schema_editor):
    """Reintroduce the `worker` role (dropped by 0014 when worker accounts
    did not exist). Worker provisioning issues invite tokens with this role;
    redemption assigns it to the new profile."""
    Role = apps.get_model('complaints', 'Role')
    Role.objects.get_or_create(role_name='worker')


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0022_pendingtransitionnotice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitetoken",
            name="worker",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invite_tokens",
                to="complaints.worker",
            ),
        ),
        migrations.RunPython(recreate_worker_role, reverse_code=migrations.RunPython.noop),
    ]
