# Generated by Django 5.2.7 on 2026-09-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0023_invitetoken_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaintevent",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaint_events",
                to="complaints.worker",
            ),
        ),
    ]