# Generated by Django 5.2.7 on 2026-09-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0024_complaint_event_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_complaints', to='complaints.userprofile'),
        ),
    ]
